codecov:
  require_ci_to_pass: true


coverage:
  precision: 3
  round: down
  range: "70...90" # Colour range - 70% coverage (and below) is solid red, 90% coverage (and above) is solid green.


comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
